CREATE DATABASE BDEMPRESA
USE BDEMPRESA

CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_DEPARTAMENTO VARCHAR (50) NOT NULL
)
CREATE TABLE EMPREGADO(
	IDEMPREGADO INT NOT NULL PRIMARY KEY IDENTITY,
	IDDEPARTAMENTO INT CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY REFERENCES DEPARTAMENTO(IDDEPARTAMENTO),
	NOME VARCHAR (50) NOT NULL,
	CPF CHAR (11) NOT NULL
)
CREATE TABLE DEPENDENTE(
	IDDEPENDENTE INT NOT NULL PRIMARY KEY IDENTITY,
	IDEMPREGADO INT FOREIGN KEY REFERENCES EMPREGADO(IDEMPREGADO),
	NOME VARCHAR (50) NOT NULL
)
CREATE TABLE LOCALIZACAO(
	IDLOCALIZACAO INT NOT NULL PRIMARY KEY IDENTITY,
	IDDEPARTAMENTO INT FOREIGN KEY REFERENCES DEPARTAMENTO(IDDEPARTAMENTO),
	LOCAL_DEPARTAMENTO VARCHAR (50) NOT NULL
)
CREATE TABLE PROJETO(
	IDPROJETO INT NOT NULL PRIMARY KEY IDENTITY,
	IDDEPARTAMENTO INT FOREIGN KEY REFERENCES DEPARTAMENTO(IDDEPARTAMENTO),
	NOME_PROJETO VARCHAR(50) NOT NULL
)
CREATE TABLE REGISTRO_PROJETO(
	IDREGISTRO INT NOT NULL PRIMARY KEY IDENTITY,
	IDEMPREGADO INT FOREIGN KEY REFERENCES EMPREGADO(IDEMPREGADO),
	IDPROJETO INT FOREIGN KEY REFERENCES PROJETO(IDPROJETO)
)
SELECT * FROM DEPENDENTE
SELECT * FROM EMPREGADO
SELECT * FROM DEPARTAMENTO
SELECT * FROM LOCALIZACAO
SELECT * FROM PROJETO
SELECT * FROM REGISTRO_PROJETO

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO) VALUES ('FINANÇAS'), ('TECNOLOGIA'), ('COMUNICAÇÃO')

INSERT INTO EMPREGADO (IDDEPARTAMENTO, NOME, CPF) VALUES (2, 'ROBERTO ANIBAL', 43209830902), (1, 'CREUZA MARIA', 43209833302), (3, 'NELSON PERERA', 43209838273)

INSERT INTO DEPENDENTE (IDEMPREGADO, NOME) VALUES (1, 'MATHEUS MARCOS'), (2, 'YASMIN SILVA'), (3, 'JORGE BENJOR')

INSERT INTO LOCALIZACAO(IDDEPARTAMENTO, LOCAL_DEPARTAMENTO) VALUES (2, 'PARANA'), (2, 'SÃO PAULO'), (3, 'RIO DE JANEIRO')

INSERT INTO PROJETO (IDDEPARTAMENTO, NOME_PROJETO) VALUES (1, 'CODEXP'), (3, 'ARTE RUPESTRE'), (2, 'LIBRAS PARA TODOS')

INSERT INTO REGISTRO_PROJETO(IDEMPREGADO, IDPROJETO) VALUES (1, 2), (3, 2), (2, 2)




