CREATE DATABASE BDTIME
USE BDTIME

CREATE TABLE EQUIPE(
	IDEQUIPE INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_EQUIPE VARCHAR (50) NOT NULL
)
CREATE TABLE JOGADOR(
	IDJOGADOR INT NOT NULL PRIMARY KEY IDENTITY,
	IDEQUIPE INT NOT NULL FOREIGN KEY REFERENCES EQUIPE(IDEQUIPE),
	NOME VARCHAR (50) NOT NULL
)
SELECT * FROM EQUIPE
SELECT * FROM JOGADOR

INSERT INTO EQUIPE (NOME_EQUIPE) VALUES ('Oklahoma City Thunder'), ('New Orleans Pelicans'), ('Milwaukee Bucks')
INSERT INTO JOGADOR(IDEQUIPE, NOME) VALUES (1, 'Steven Adams'), (2, 'Zion Williamson'), (3, 'Giannis Antetokounmpo')

DELETE FROM JOGADOR WHERE IDJOGADOR = 6