---------------------------------------------COMANDOS DDL(Data Definition Language)---------------------------------------------

--CRIAR UM BANCO DE DADOS
CREATE DATABASE BDVETERINARIA
--COLOCAR EM USO
USE BDVETERINARIA
--CRIAR TABELA 

CREATE TABLE DONO (
	CODDONO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CPF CHAR(11) NOT NULL UNIQUE,
	EMAIL VARCHAR(50),
	TELEFONE CHAR(14),
	SALARIO MONEY
	)

CREATE TABLE ANIMAL (
	CODANIMAL INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(30),
	IDADE INT,
	RACA VARCHAR(25),
	OBS TEXT,
	CODDONO INT CONSTRAINT FK_DONO FOREIGN KEY  REFERENCES DONO (CODDONO)
)

--EXCLUIR TABELA
DROP TABLE ANIMAL

--EXCLUIR UM CAMPO DA TABELA
ALTER TABLE ANIMAL DROP COLUMN OBS

--ADICIONAR UM NOVO CAMPO NA TABELA
ALTER TABLE ANIMAL ADD OBS TEXT

--ALTERAR UM TIPO DE DADOS DE UM CAMPO DA TABELA
ALTER TABLE ANIMAL ALTER COLUMN NOME VARCHAR(50)

--ADICIONAR CHAVE ESTRANGEIRA POR ALTER TABLE
ALTER TABLE ANIMAL ADD CONSTRAINT FK_DONO FOREIGN KEY (CODDONO)
REFERENCES DONO (CODDONO)

--CONSULTAR TODOS OS CADASTROS 
SELECT * FROM DONO --TODOS OS CAMPOS
SELECT NOME, CPF, SALARIO FROM DONO --CAMPOS ESPEC�FICOS

------------------------------------------FIM DDL------------------------------------------

---------------------------------------------COMANDOS DQL (Data Query Language)---------------------------------------------
--EXEMPLO DE CONSULTA COM OPERADORES 
WHERE --ONDE

SELECT * FROM DONO WHERE NOME = 'Luander'

SELECT * FROM DONO WHERE SALARIO > 600

SELECT * FROM DONO WHERE NOME = 'Luander' AND SALARIO > 500
--ORDENAR CONSULTA (ODER BY)

SELECT * FROM DONO ORDER BY  NOME

SELECT * FROM DONO ORDER BY  NOME DESC

SELECT * FROM DONO ORDER BY SALARIO

SELECT * FROM DONO WHERE SALARIO > 1000 ORDER BY SALARIO DESC

--FUNÇÕES STRING

LEN() - CONTA A QUANTIDADE DE CARACTERES EM UM CAMPO

SELECT LEN(NOME) FROM DONO

UPPER() - TRANSFORMA EM LETRAS MAIUSCULAS

SELECT CODDONO, UPPER(NOME), CPF, EMAIL, TELEFONE, SALARIO FROM DONO

LOWER() -TRANSFORMA EM LETRAS MINUSCULAS

SELECT CODDONO, LOWER(NOME), CPF, EMAIL, TELEFONE, SALARIO FROM DONO

SELECT CODDONO, UPPER(NOME), CPF, LOWER(EMAIL), TELEFONE, SALARIO FROM DONO

--FUN��ES N�MERICAS

MAX() - MAIOR NUMERO / VALOR

SELECT MAX(SALARIO) FROM DONO

MIN() - MENOR NUMERO / VALOR

SELECT MIN(SALARIO) FROM DONO

AVG() - MEDIA DE VALORES

SELECT AVG(SALARIO) FROM DONO

COUNT() - CONTAR QUANTIDADE DE CADASTROS

SELECT COUNT(*) FROM DONO

--FAZER CONTAS EM SQL
SELECT NOME, SALARIO + 1000 FROM DONO

SELECT * FROM DONO

---------------------------------------------FIM DQL---------------------------------------------

---------------------------------------------COMANDOS DML(Data Manipulation Language)---------------------------------------------
--REALIZAR UM CADASTRO NA TABELA
INSERT INTO DONO 
	(NOME, CPF, EMAIL, TELEFONE, SALARIO)
	VALUES 
	('Kevin', '12345678909','kevin@gmail.com','(11)4002-8922',1500.99)

INSERT INTO DONO 
	(NOME, CPF, EMAIL, TELEFONE, SALARIO)
	VALUES 
	('Luander', '12345678902','bluehair@gmail.com','(11)4003-8923',500.99)

--CADASTRO COM CHAVE ESTRANGEIRA
INSERT INTO ANIMAL 
	(NOME, IDADE, RACA, CODDONO,OBS)
	VALUES
	('Rat�o',18,'Predador',2,'vegano')

--CONSULTA COM FILTROS 
--OPERADORES DE COMPARAÇÃO: >, < >= <=, <>, =
--OPERADORES LÓGICOS: AND, OR, NOT

--EXCLUIR CADASTROS

DELETE FROM ANIMAL -- EXCLUIR TODOS OS CADASTROS DA TABELA

DELETE FROM ANIMAL WHERE CODANIMAL = 5

DELETE FROM ANIMAL WHERE IDADE > 50

DELETE FROM DONO WHERE CODDONO = 1

--ATUALIZAÇÃO DE CADASTROS

UPDATE DONO SET SALARIO = 2500 --ALTERAR TODOS

UPDATE DONO SET SALARIO = 3500 WHERE CODDONO = 2

UPDATE DONO SET SALARIO = 3500, EMAIL = 'luander@gmail.com', NOME = 'Luander New Blue Hair' WHERE CODDONO = 2


UPDATE DONO SET SALARIO = SALARIO + 1000
---UPDATE DONO SET SALARIO += 1000


