--CRIAR UM BANCO DE DADOS
CREATE DATABASE BDBOLETIM
--USAR BOLETIM
USE BDBOLETIM
--EXCLUIR
DROP DATABASE BDBOLETIM

--CRIANDO TABELA
CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	RA VARCHAR(10) NOT NULL,
	IDADE INT
)
CREATE TABLE MATERIA(
	IDMATERIA INT NOT NULL PRIMARY KEY IDENTITY,
	MATERIA VARCHAR(50),
)
CREATE TABLE TRABALHO(
	IDTRABALHO INT NOT NULL PRIMARY KEY IDENTITY,
	IDMATERIA INT CONSTRAINT FK_MATERIA FOREIGN KEY REFERENCES MATERIA (IDMATERIA),
	IDALUNO INT CONSTRAINT FK_ALUNO FOREIGN KEY REFERENCES ALUNO (IDALUNO),
	NOTA DECIMAL,
)
DROP TABLE TRABALHO