CREATE DATABASE BDCAMISETA
USE BDCAMISETA

CREATE TABLE MARCA(
	IDMARCA INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_MARCA VARCHAR(30) NOT NULL
)
CREATE TABLE COR(	
	IDCOR INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_COR VARCHAR(30) NOT NULL
)
CREATE TABLE TAMANHO(
	IDTAMANHO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_TAMANHO VARCHAR(5) NOT NULL
)
CREATE TABLE CAMISETA(
	IDCAMISETA INT NOT NULL PRIMARY KEY IDENTITY,
	IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCA(IDMARCA),
	IDCOR INT NOT NULL FOREIGN KEY REFERENCES COR(IDCOR),
	IDTAMANHO INT NOT NULL FOREIGN KEY REFERENCES TAMANHO(IDTAMANHO)
)

SELECT MARCA.NOME_MARCA FROM MARCA
SELECT * FROM MARCA

SELECT TAMANHO.NOME_TAMANHO FROM TAMANHO
SELECT * FROM TAMANHO

SELECT COR.NOME_COR FROM COR
SELECT * FROM COR

SELECT * FROM CAMISETA


--INNER JOIN
SELECT CAMISETA.IDCAMISETA, MARCA.NOME_MARCA FROM CAMISETA
INNER JOIN MARCA ON MARCA.IDMARCA = CAMISETA.IDMARCA

SELECT CAMISETA.IDCAMISETA, COR.NOME_COR FROM CAMISETA
INNER JOIN COR ON COR.IDCOR = CAMISETA.IDCOR

SELECT CAMISETA.IDCAMISETA, TAMANHO.NOME_TAMANHO FROM CAMISETA
INNER JOIN TAMANHO ON TAMANHO.IDTAMANHO = CAMISETA.IDTAMANHO


INSERT INTO COR(NOME_COR) VALUES ('BRANCA'), ('VERMELHA'), ('AZUL'), ('ROXO'), ('VERDE')
INSERT INTO TAMANHO(NOME_TAMANHO) VALUES ('P'), ('M'), ('G'), ('GG')
INSERT INTO MARCA(NOME_MARCA) VALUES ('NIKE'), ('LAKAI'), ('GIRL')
INSERT INTO CAMISETA(IDMARCA, IDCOR, IDTAMANHO) VALUES (1,2,3), (2,1,3), (3,2,1), (1,3,2), (1,1,1)

--ALTERAÇÃO DE MARCA
UPDATE MARCA SET NOME_MARCA='ADIDAS' WHERE IDMARCA= 1 
UPDATE MARCA SET NOME_MARCA='DROPDEAD' WHERE IDMARCA= 2

DELETE FROM CAMISETA WHERE IDCAMISETA = (SELECT MAX(IDCAMISETA) FROM CAMISETA)



