CREATE DATABASE BDCOMPRA
USE BDCOMPRA

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR (50) NOT NULL
)
CREATE TABLE PRODUTO(
	IDPRODUTO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_PRODUTO VARCHAR(50) NOT NULL
)
CREATE TABLE COMPRA(
	IDCOMPRA INT NOT NULL PRIMARY KEY IDENTITY,
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE),
	IDPRODUTO INT NOT NULL FOREIGN KEY REFERENCES PRODUTO(IDPRODUTO)
)
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM COMPRA

INSERT INTO CLIENTE (NOME) VALUES ('JUREMIAS CAVALCANTE'), ('CREUZA GUIMARAES'), ('ROGER MARTINS')
INSERT INTO PRODUTO (NOME_PRODUTO) VALUES ('BANANA'), ('MAÇA'), ('MELÃO')
INSERT INTO COMPRA (IDCLIENTE, IDPRODUTO) VALUES (2,2), (3,1), (1,3)