CREATE DATABASE BDMATRICULA
USE BDMATRICULA

CREATE TABLE CANDIDATO(
	IDCANDIDATO INT NOT NULL PRIMARY KEY IDENTITY,
	IDCURSO INT CONSTRAINT FK_CURSO FOREIGN KEY REFERENCES CURSO(IDCURSO),
	NOME VARCHAR(50) NOT NULL,
	IDADE INT
)
CREATE TABLE CURSO(
	IDCURSO INT NOT NULL PRIMARY KEY IDENTITY,
	NOMECURSO VARCHAR(50) NOT NULL,
	PERIODO VARCHAR (10) NOT NULL
)

INSERT INTO CANDIDATO(NOME,IDADE, IDCURSO) VALUES('Rubão', 21, 2)
INSERT INTO CANDIDATO(NOME, IDADE, IDCURSO) VALUES('Paty', 25, 3)
INSERT INTO CANDIDATO(NOME, IDADE, IDCURSO) VALUES('Nilson', 25, 1)


INSERT INTO CURSO (NOMECURSO, PERIODO) VALUES ('Excel', 'Noturno')
INSERT INTO CURSO (NOMECURSO, PERIODO) VALUES ('Java', 'Matutino')
INSERT INTO CURSO (NOMECURSO, PERIODO) VALUES ('Cobol', 'Vesperino')

DELETE FROM CANDIDATO WHERE IDCANDIDATO= 2
SELECT * FROM CANDIDATO
SELECT * FROM CURSO