CREATE DATABASE BDDIRETOR
USE BDDIRETOR

CREATE TABLE DIRETOR(
	IDDIRETOR INT NOT NULL PRIMARY KEY IDENTITY,
	IDDEPARTAMENTO INT FOREIGN KEY REFERENCES DEPARTAMENTO(IDDEPARTAMENTO),
	NOME VARCHAR (50) NOT NULL
)
CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_DEPARTAMENTO VARCHAR (50) NOT NULL,
)
SELECT * FROM DIRETOR
SELECT * FROM DEPARTAMENTO

INSERT INTO DEPARTAMENTO (NOME_DEPARTAMENTO) VALUES ('TECNOLOGIA'), ('ADMINISTRACAO'), ('FINANCAS')

INSERT INTO DIRETOR (IDDEPARTAMENTO, NOME) VALUES (2, 'LUCAS GREGORIO'), (3, 'NELSON RIBIERO'), (1, 'VALDEMIR PAZ')