CREATE DATABASE BDESCOLA
USE BDESCOLA

CREATE TABLE RESPONSAVEL(
	IDRESPONSAVEL INT NOT NULL PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL
)
CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL PRIMARY KEY IDENTITY,
	IDRESPONSAVEL INT CONSTRAINT FK_RESPONSAVEL FOREIGN KEY REFERENCES RESPONSAVEL(IDRESPONSAVEL),
	IDTURMA INT CONSTRAINT FK_TURMA FOREIGN KEY REFERENCES TURMA(IDTURMA),
	NOME VARCHAR(50) NOT NULL
)
CREATE TABLE TURMA(
	IDTURMA INT NOT NULL PRIMARY KEY IDENTITY,
	TURMA VARCHAR(30) NOT NULL
)
SELECT * FROM TURMA
SELECT * FROM RESPONSAVEL
SELECT * FROM ALUNO
INSERT INTO RESPONSAVEL(NOME) VALUES ('Alex'),('Juremias'),('Cleiton')
INSERT INTO TURMA (TURMA) VALUES ('Turma A'), ('Turma B'), ('Turma C')
INSERT INTO ALUNO (IDRESPONSAVEL, IDTURMA, NOME) VALUES (2, 3, 'Maicon'), (3, 1, 'Natalia'), (1, 2, 'Alex')
